In [1]:

from pylbm import lbm
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})


In [110]:
eps = 0.01
r_value = 0.5
i_dim, j_dim, v_dim = 5, 10, 9
omega = .3
r_ij = lbm.rho_init(i_dim=i_dim, j_dim=j_dim, r_mean=r_value, eps=eps)
u_ija = lbm.local_avg_velocity_init(i_dim=i_dim, j_dim=j_dim, u_mean=0.5, eps=0.01)
f_ijc = lbm.f_eq(u_ija=u_ija, r_ij=r_ij)


In [111]:
epochs =1500

print(u_ija.T)
for _ in range(epochs):
    f_ijc = lbm.stream(f_ijc=f_ijc)
    f_ijc, u_ija = lbm.collision(f_ijc=f_ijc, omega=omega)
print("new")
print(u_ija.T)

[[[0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]]

 [[0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]
  [0.500 0.507 0.510 0.507 0.500]]]
new
[[[-3.364 -0.078 0.947 0.661 -1.007]
  [-1.113 0.036 0.649 -0.636 -3.872]
  [7.669 0.932 -0.929 0.058 -3.643]
  [-0.247 1.949 -0.956 0.442 0.120]
  [-1.573 1.723 0.101 0.535 0.497]
  [-1.422 -0.012 -0.751 0.370 0.226]
  [-1.263 -1.042 -0.018 0.158 0.891]
  [-0.940 -0.019 0.356 -0.046 0.284]
  [-2.025 -0.076 -0.