# Numpy methods for Streaming and Collision

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### The streaming operator
For this purpose we need the numpy method roll of arrays

In [3]:
# Create an array and print it
a = np.arange(5*7)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [4]:
# reshape it to a rectangular array
b = a.reshape((5,7))
print(b)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [5]:
%matplotlib notebook
plt.rcParams['xtick.labelbottom'] = False
plt.rcParams['xtick.labeltop'] = True
# Roll it in different direction
c = np.roll(b,shift = c_ca[2],axis = (1,0))
print(c)
#
column_labels = list('0123456')
row_labels = list('01234')
#data = np.random.rand(5, 6)
fig, ax = plt.subplots()
data = c/a[-1]
heatmap = ax.pcolor(data, cmap=plt.cm.Reds)
# put the major ticks at the middle of each cell
ax.set_xticks(np.arange(data.shape[1]) + 0.5, minor=False)
ax.set_yticks(np.arange(data.shape[0]) + 0.5, minor=False)
ax.invert_yaxis()
ax.xaxis.tick_top()
#
ax.set_xticklabels(column_labels, minor=False)
ax.set_yticklabels(row_labels, minor=False)
ax.set_ylabel('axis 0, first  index')
ax.set_title('axis 1, second index')
plt.show() 

NameError: name 'c_ca' is not defined

In [6]:
f_cij = np.ones((9,5,7))
c_ca = np.array([[0, 1, 0, -1, 0, 1, -1, -1, 1],
                 [0, 0, -1, 0 ,1, -1, -1, 1, 1]]).T     # These are the velocities of the channels
#
for k in np.arange(9):
    f_cij[k] = np.roll(f_cij[k],c_ca[k],axis = (1,0))

### Collision operator
To calculate the outcome of the collision 
$$ f_i+\omega(f_i^{eq}-f_i)$$
We need to know the average velocity at $\mathbf{r}$ and the denisty $n(\mathbf{r})$.

In [ ]:
f_cij = np.ones((9,5,7))
c_ca = np.array([[0, 1, 0, -1, 0, 1, -1, -1, 1],
                 [0, 0, -1, 0 ,1, -1, -1, 1, 1]]).T     # These are the velocities of the channels

In [ ]:
w_c = np.array([4/9,1/9,1/9,1/9,1/9,1/36,1/36,1/36,1/36])  # equilibrium occupation numbers

In [ ]:
for c in np.arange(9): f_cij[c] = w_c[c]

In [ ]:
f_cij[:] = w_c[:,np.newaxis,np.newaxis]

In [ ]:
f_cij[1] = f_cij[1]+0.01
f_cij[3] = f_cij[3]-0.01

In [ ]:
u_aij = np.einsum('cij,ca->aij',f_cij,c_ca)

In [ ]:
u_aij

In [ ]:
rho_ij = np.einsum('cij->ij',f_cij)

In [ ]:
rho_ij